package br.com.alkord.utilitarioIntegracao.integracaoViaArquivo.beans.produto;

public class ProdutoNCM {

	private String CODIGO;
	private String CEST;
	private String TOTAL_TRIBUTOS_FEDERAIS_NACIONAL;
	private String TOTAL_TRIBUTOS_FEDERAIS_IMPORTADO;
	private String TOTAL_TRIBUTOS_ESTADUAIS;
	private String TOTAL_TRIBUTOS_MUNICIPAIS;

	public String getCODIGO() {
		return CODIGO;
	}

	public void setCODIGO(String CODIGO) {
		this.CODIGO = CODIGO;
	}

	public String getCEST() {
		return CEST;
	}

	public void setCEST(String CEST) {
		this.CEST = CEST;
	}

	public String getTOTAL_TRIBUTOS_FEDERAIS_NACIONAL() {
		return TOTAL_TRIBUTOS_FEDERAIS_NACIONAL;
	}

	public void setTOTAL_TRIBUTOS_FEDERAIS_NACIONAL(String TOTAL_TRIBUTOS_FEDERAIS_NACIONAL) {
		this.TOTAL_TRIBUTOS_FEDERAIS_NACIONAL = TOTAL_TRIBUTOS_FEDERAIS_NACIONAL;
	}

	public String getTOTAL_TRIBUTOS_FEDERAIS_IMPORTADO() {
		return TOTAL_TRIBUTOS_FEDERAIS_IMPORTADO;
	}

	public void setTOTAL_TRIBUTOS_FEDERAIS_IMPORTADO(String TOTAL_TRIBUTOS_FEDERAIS_IMPORTADO) {
		this.TOTAL_TRIBUTOS_FEDERAIS_IMPORTADO = TOTAL_TRIBUTOS_FEDERAIS_IMPORTADO;
	}

	public String getTOTAL_TRIBUTOS_ESTADUAIS() {
		return TOTAL_TRIBUTOS_ESTADUAIS;
	}

	public void setTOTAL_TRIBUTOS_ESTADUAIS(String TOTAL_TRIBUTOS_ESTADUAIS) {
		this.TOTAL_TRIBUTOS_ESTADUAIS = TOTAL_TRIBUTOS_ESTADUAIS;
	}

	public String getTOTAL_TRIBUTOS_MUNICIPAIS() {
		return TOTAL_TRIBUTOS_MUNICIPAIS;
	}

	public void setTOTAL_TRIBUTOS_MUNICIPAIS(String TOTAL_TRIBUTOS_MUNICIPAIS) {
		this.TOTAL_TRIBUTOS_MUNICIPAIS = TOTAL_TRIBUTOS_MUNICIPAIS;
	}
}
